
name: Self-hosted PC Check

on:
  workflow_dispatch:

jobs:
  pc-check:
    runs-on: self-hosted

    steps:
      - name: Check Windows PC
        shell: powershell
        run: |
          Write-Host "Self-hosted runner is working"
          Get-CimInstance Win32_Processor |
            Select-Object Name, NumberOfCores, NumberOfLogicalProcessors
          Get-CimInstance Win32_OperatingSystem |
            Select-Object TotalVisibleMemorySize, FreePhysicalMemory
          Get-PSDrive C |
            Select-Object Name, Used, Free

